CREATE TABLE productos (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_comercial VARCHAR2(100) NOT NULL,
    categoria_negocio VARCHAR2(50) NOT NULL,
    precio_venta NUMBER(10,2) DEFAULT 0 CHECK (precio_venta >= 0),
    stock_disponible NUMBER DEFAULT 0 NOT NULL,
    fecha_alta DATE DEFAULT SYSDATE,
    estado_publicacion VARCHAR2(8) DEFAULT 'ACTIVO' CHECK (estado_publicacion IN ('ACTIVO', 'INACTIVO')),
    codigo_sku VARCHAR2(50) UNIQUE NOT NULL,
    usuario_creacion VARCHAR2(30) DEFAULT USER,
    tipo_iva NUMBER DEFAULT 21 CHECK (tipo_iva >= 0 AND tipo_iva <= 100)
);

INSERT INTO productos (nombre_comercial, categoria_negocio, precio_venta, stock_disponible, estado_publicacion, codigo_sku, usuario_creacion, tipo_iva)
VALUES ('Laptop Pro 15', 'TECNOLOGIA', 1200.00, 5, 'ACTIVO', 'TEC67890', USER, 21);

INSERT INTO productos (nombre_comercial, categoria_negocio, precio_venta, stock_disponible, estado_publicacion, codigo_sku, usuario_creacion, tipo_iva)
VALUES ('Aspiradora Ultra', 'HOGAR', 150.00, 0, 'ACTIVO', 'HOG11111', USER, 21);

INSERT INTO productos (nombre_comercial, categoria_negocio, precio_venta, stock_disponible, estado_publicacion, codigo_sku, usuario_creacion, tipo_iva)
VALUES ('Microondas X200', 'HOGAR', 120.00, 3, 'ACTIVO', 'HOG22222', USER, 21);

INSERT INTO productos (nombre_comercial, categoria_negocio, precio_venta, stock_disponible, estado_publicacion, codigo_sku, usuario_creacion, tipo_iva)
VALUES ('Balón Oficial', 'DEPORTE', 0, 15, 'INACTIVO', 'DEP33333', USER, 21);




INSERT INTO productos (nombre_comercial, categoria_negocio, precio_venta, stock_disponible, estado_publicacion, codigo_sku, usuario_creacion, tipo_iva)
VALUES ( 'Tablet Económica', 'TECNOLOGIA',  -100.00,  10,  'ACTIVO',  'TEC99999',  USER,  21);

UPDATE productos
SET precio_venta = ROUND(precio_venta * 1.05, 2)
WHERE categoria_negocio = 'TECNOLOGIA';

UPDATE productos
SET estado_publicacion = 'INACTIVO'
WHERE stock_disponible = 0;




